In [1]:
import numpy as np

In [3]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
#乱数　random
a = np.random.random((3,2))
a

array([[0.65185878, 0.69941108],
       [0.67501064, 0.03410744],
       [0.48441549, 0.30748655]])

In [10]:
#シード値の指定
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [12]:
#rand
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [15]:
#randint
np.random.seed(123)
np.random.randint(1,20)

14

In [16]:
np.random.seed(123)
np.random.randint(1,30, (3,3))

array([[14,  3, 29],
       [ 3,  7, 18],
       [20, 11, 28]])

In [17]:
#uniform
np.random.seed(123)
np.random.uniform(0.0, 5.0, size=(3,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ],
       [4.90382099, 3.42414869, 2.40465951]])

In [18]:
#第一引数と第二引数を省略
np.random.seed(123)
np.random.uniform(size=(3,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ]])

In [19]:
#randn 正規分布
np.random.seed(123)
np.random.randn(5,3)

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654],
       [-2.42667924, -0.42891263,  1.26593626],
       [-0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196]])