In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [7]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [12]:
#変形
c1 = np.array([[0,1,2],[3,4,5]])
c1

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
#戻す
c2 = c1.ravel()

In [17]:
c２

array([0, 1, 2, 3, 4, 5])

In [18]:
#インデックスとスライス
i = np.array([1,2,3,4,5,6])
i

array([1, 2, 3, 4, 5, 6])

In [19]:
i[5]

6

In [20]:
i[3:]

array([4, 5, 6])

In [22]:
i[:2]

array([1, 2])

In [23]:
i[-1]

6

In [24]:
i2 = np.array([[1,2,3],[4,5,6]])
i2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
i2[0]

array([1, 2, 3])

In [29]:
i2[1,2]

6

In [30]:
i2[:,2]
i2[1,:]

array([4, 5, 6])

In [37]:
i2[0,1:]
i2[:,[0,2]]

array([[1, 3],
       [4, 6]])