In [1]:
import numpy as np

In [3]:
#ゼロ
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#１
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#指定地で埋める
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [10]:
np.full((2,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [11]:
#欠損値
np.nan

nan

In [12]:
np.array([1,2, np.nan])

array([ 1.,  2., nan])

In [13]:
#範囲指定での均等割り
np.linspace(0,2,6)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [14]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [15]:
#差分
a = np.array([2,2,6,1,3,10])
np.diff(a)

array([ 0,  4, -5,  2,  7])

In [19]:
# 配列の連結
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate([arr1, arr2])
arr3

array([1, 2, 3, 4, 5, 6])

In [23]:
#列の追加
b1 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[10],[20]])
b1
b2

array([[10],
       [20]])

In [24]:
np.concatenate([b1, b2], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [25]:
#hstack
np.hstack([b1,b2])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [26]:
#行の追加
c1 = np.array([1,2,3])
c2 = np.array([[4,5,6],[7,8,9]])

In [27]:
c3 = np.vstack([c1, c2])
c3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
#二次元配列の分割 列方向
first, second = np.hsplit(c3, [2])

In [29]:
first

array([[1, 2],
       [4, 5],
       [7, 8]])

In [30]:
second

array([[3],
       [6],
       [9]])

In [34]:
# 行方向の分割
third, fourth = np.vsplit(c3, [2])

In [35]:
third

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
fourth

array([[7, 8, 9]])

In [37]:
#転置
c２

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
c2.T

array([[4, 7],
       [5, 8],
       [6, 9]])

In [39]:
#次元の追加
a = np.array([1,2,3])

In [40]:
# 行方向の指定
a[np.newaxis, :]

array([[1, 2, 3]])

In [42]:
#列方向の指定
a[:, np.newaxis]

array([[1],
       [2],
       [3]])