In [1]:
import numpy as np

In [3]:
#ゼロ
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#１
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#指定地で埋める
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [10]:
np.full((2,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [11]:
#欠損値
np.nan

nan

In [12]:
np.array([1,2, np.nan])

array([ 1.,  2., nan])

In [13]:
#範囲指定での均等割り
np.linspace(0,2,6)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [14]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])