In [1]:
import numpy as np

In [7]:
# 問１５
a = np.array([7, 8, 9])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape, b[0:1, [1,2]])

(3,) [[2 3]]


In [9]:
# 問17
c = np.full((2, 3), np.pi).T.ravel()
c

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265])

In [11]:
d = np.linspace(0, 1.25, 6)
d

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25])

In [13]:
e = np.concatenate([c, d], axis=0)
e

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 0.        , 0.25      , 0.5       , 0.75      ,
       1.        , 1.25      ])

In [14]:
print(c[1], e[-2])

3.141592653589793 1.0
