In [1]:
import numpy as np

In [9]:
# 15問
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b

array([7, 8, 9])

In [12]:
print(a[-1:, [1,2]])

[[5 6]]


In [13]:
b.shape

(3,)

In [14]:
a.shape

(2, 3)

In [27]:
# 14問
fla = np.array([1, 2, 3])
rav = np.array([4, 5, 6])

# 参照を渡す
copied_fla = fla.flatten()
# コピーを渡す
copied_rav = rav.ravel()

In [28]:
copied_fla

array([1, 2, 3])

In [29]:
copied_rav

array([4, 5, 6])

In [30]:
copied_fla[0] = 10
copied_rav[0] = 20

In [31]:
copied_fla

array([10,  2,  3])

In [32]:
copied_rav

array([20,  5,  6])

In [25]:
fla

array([1, 2, 3])

In [26]:
rav

array([20,  5,  6])

In [37]:
# 16問
c = np.arange(1, 10, 2)
d = np.eye(6)
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
print(c[-1], d[3, 3])

9 1.0


In [44]:
# 17問
e = np.full((2, 3), np.pi).T.ravel()
e

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265])

In [48]:
f = np.linspace(0, 1, 5)
g = np.hstack([e, f])

In [46]:
g

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 0.        , 0.25      , 0.5       , 0.75      ,
       1.        ])

In [49]:
print(e[-1], g[-2])

3.141592653589793 0.75


In [53]:
full_arr = np.full(3, 4)
full_arr

array([4, 4, 4])