In [1]:
import numpy as np

In [9]:
# 15問
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b

array([7, 8, 9])

In [12]:
print(a[-1:, [1,2]])

[[5 6]]


In [13]:
b.shape

(3,)

In [14]:
a.shape

(2, 3)