In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

In [6]:
# 36問
boston = load_boston()
X, y = boston.data, boston.target

In [7]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [8]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

In [10]:
X_train

array([[2.21880e-01, 2.00000e+01, 6.96000e+00, ..., 1.86000e+01,
        3.90770e+02, 6.58000e+00],
       [5.36000e-02, 2.10000e+01, 5.64000e+00, ..., 1.68000e+01,
        3.96900e+02, 5.28000e+00],
       [6.88800e-02, 0.00000e+00, 2.46000e+00, ..., 1.78000e+01,
        3.96900e+02, 9.45000e+00],
       ...,
       [3.51140e-01, 0.00000e+00, 7.38000e+00, ..., 1.96000e+01,
        3.96900e+02, 7.70000e+00],
       [9.18702e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 2.36000e+01],
       [4.55587e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.54700e+02, 7.12000e+00]])

In [11]:
X_test

array([[5.11358e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        2.60000e+00, 1.01100e+01],
       [5.73500e-02, 0.00000e+00, 4.49000e+00, ..., 1.85000e+01,
        3.92300e+02, 6.53000e+00],
       [3.57800e-02, 2.00000e+01, 3.33000e+00, ..., 1.49000e+01,
        3.87310e+02, 3.76000e+00],
       ...,
       [1.49632e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.41600e+02, 1.32800e+01],
       [1.22472e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        2.46500e+01, 1.56900e+01],
       [3.56868e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.93370e+02, 1.43600e+01]])

In [12]:
lr = LinearRegression()
lr

LinearRegression()

In [13]:
lr.fit(X_train, y_train)
lr

LinearRegression()

In [14]:
y_pred = lr.predict(X_test)
y_pred

array([15.4757088 , 27.85786595, 39.71821366, 17.94591734, 30.19441873,
       37.51057831, 25.20492485, 11.29301795, 13.93325033, 32.10798674,
       28.51346127, 19.10242965, 14.16909335, 30.59883198, 16.91765089,
       21.57521646, 20.56956106, 38.0388848 , 18.28489886, 15.44455502,
       13.942728  , 22.89202676, 33.08289616, 38.85747118, 29.91747968,
       22.34030137, 17.88075723, 20.6598468 , 23.37690089, 20.51319684,
       25.78620928, 33.83339852, 15.33132641, 21.79161378, 24.14376798,
       35.2106862 , 29.20302521, 18.566505  , 13.9622867 , 38.63492008,
       31.18122326, 19.10959362, 19.1273964 , 39.74779582,  8.86534866,
       27.28051165, 19.04476095, 25.44873252, 15.50076478, 26.17581245,
       33.69571146, 24.40124874, 19.39414746, 12.55330545, 24.50462883,
       18.21889479, 10.63052092,  2.28680811, 31.72266364, 13.46355579,
       20.09462113, 22.38725561, 19.98251601, 17.86587813, 24.34154548,
       26.93269765, 25.82034717, 22.2255162 , 24.67832008, 30.36