In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        'A': [1,2,3,4,5],
        'B': [100,200,300,400,500]
    }
)
df

A    B
0  1  100
1  2  200
2  3  300
3  4  400
4  5  500

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
# 分散正規化のインスタンスを生成
stdsc = StandardScaler()
# 分散正規化を実行
stdsc.fit(df)
stdsc.transform(df)

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
# 最小最大正規化のインスタンスの生成
mmsc = MinMaxScaler()
mmsc.fit(df)
mmsc.transform(df)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [7]:
from sklearn.datasets import load_iris

In [8]:
# Irisデータセットを読み込む
iris = load_iris()
X, y = iris.data, iris.target

# 先頭5行を表示
print('X:')
print(X[:5, :])
print('y:')
print(y[:5])

X:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y:
[0 0 0 0 0]


In [10]:
# Irisのデータセットの形状
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
# 学習データとテストデータに分割
# データセット全体が150,その内学習データセットが70%,テストデータセットが30%
X_train, X_test, y_train, y_test = train_test_split(
                                    X, y, test_size=0.3, random_state=123)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)
