In [1]:
import numpy as np
import pandas as pd

In [4]:
#サンプルのデータセットを作成
df = pd.DataFrame(
    {
        'A': [1, np.nan, 3, 4, 5],
        'B': [6, 7, 8, np.nan, 10],
        'C': [11, 12, 13, 14, 15]
    }
)
df

A     B   C
0  1.0   6.0  11
1  NaN   7.0  12
2  3.0   8.0  13
3  4.0   NaN  14
4  5.0  10.0  15

In [5]:
# 各要素が欠損値かどうか
df.isnull()

A      B      C
0  False  False  False
1   True  False  False
2  False  False  False
3  False   True  False
4  False  False  False

In [9]:
from sklearn.impute import SimpleImputer

# 平均値で欠損値を補完するインスタンスを作成
imp = SimpleImputer(strategy='mean')
# 欠損値を補完
imp.fit(df)
imp.transform(df)

array([[ 1.  ,  6.  , 11.  ],
       [ 3.25,  7.  , 12.  ],
       [ 3.  ,  8.  , 13.  ],
       [ 4.  ,  7.75, 14.  ],
       [ 5.  , 10.  , 15.  ]])

In [14]:
df = pd.DataFrame(
    {
        'A': [1,2,3,4,5],
        'B': ['a', 'b', 'a', 'b', 'c']
    }
)
df

A  B
0  1  a
1  2  b
2  3  a
3  4  b
4  5  c

In [15]:
df

A  B
0  1  a
1  2  b
2  3  a
3  4  b
4  5  c

In [16]:
from sklearn.preprocessing import LabelEncoder

# ラベルエンコーダのインスタンス作成
le = LabelEncoder()
# ラベルのエンコーディング
le.fit(df['B'])
le.transform(df['B'])

array([0, 1, 0, 1, 2])

In [17]:
# 元の値を確認
le.classes_

array(['a', 'b', 'c'], dtype=object)

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# DataFrameをコピー
df_onehot = df.copy()
# ラベルエンコーダのインスタンス化
le = LabelEncoder()
# 英語のa,b,cを1,2,3に変換
df_onehot['B'] = le.fit_transform(df_onehot['B'])
# One-Hotエンコーダのインスタンス化
onehot = ColumnTransformer([("test", OneHotEncoder(),
                            [1])], remainder='passthrough')
# One-Hotエンコーディング
onehot.fit_transform(df_onehot)

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [1., 0., 0., 3.],
       [0., 1., 0., 4.],
       [0., 0., 1., 5.]])