In [1]:
import numpy as np

In [6]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
print("a:", a) 
print("b:", b) 

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]


In [7]:
# ドット積
np.dot(b, a)

array([-4,  5])

In [8]:
b @ a

array([-4,  5])